name: linting
run-name: ${{ github.actor }}
on: [pull_request]
jobs:
    Linting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: '14'
            - run: npm ci && npm run lint
